CREATE TABLE  "CLIENTE" 
   (	"RUT" VARCHAR2(20), 
	"NOMBRE" VARCHAR2(20), 
	 CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("RUT") ENABLE
   )
/
CREATE TABLE  "USUARIO" 
   (	"RUT" VARCHAR2(20), 
	"CONTRASENNA" VARCHAR2(20), 
	"NOMBRE" VARCHAR2(20), 
	"TIPO" VARCHAR2(20), 
	"COMISION" NUMBER, 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("RUT") ENABLE
   )
/

CREATE TABLE  "VENTA" 
   (	"ID_VENTA" NUMBER, 
	"ID_CLIENTE" VARCHAR2(20), 
	"ID_USUARIO" VARCHAR2(20), 
	"MONTO_TOTAL" NUMBER, 
	"FECHA" VARCHAR2(20), 
	"TIME" VARCHAR2(20), 
	 CONSTRAINT "VENTA_PK" PRIMARY KEY ("ID_VENTA") ENABLE, 
	 CONSTRAINT "VENTA_FK" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES  "CLIENTE" ("RUT") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "VENTA_FK2" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES  "USUARIO" ("RUT") ON DELETE CASCADE ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_VENTA" 
  before insert on "VENTA"               
  for each row  
begin   
    select "VENTA_SEQ1".nextval into :NEW.ID_VENTA from dual; 
end; 

/
ALTER TRIGGER  "BI_VENTA" ENABLE
/
CREATE TABLE  "PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER, 
	"NOMBRE" VARCHAR2(20), 
	"STOCK" NUMBER, 
	"DESCRIPCION" VARCHAR2(20), 
	"CATEGORIA" VARCHAR2(20), 
	"PRECIO" NUMBER, 
	 CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_PRODUCTO" 
  before insert on "PRODUCTO"               
  for each row  
begin   
    select "PRODUCTO_SEQ1".nextval into :NEW.ID_PRODUCTO from dual; 
end; 

/

CREATE TABLE  "DETALLE_VENTA" 
   (	"ID_DETALLE_VENTA" NUMBER, 
	"ID_VENTA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	 CONSTRAINT "DETALLE_VENTA_PK" PRIMARY KEY ("ID_DETALLE_VENTA") ENABLE, 
	 CONSTRAINT "DETALLE_VENTA_FK" FOREIGN KEY ("ID_VENTA")
	  REFERENCES  "VENTA" ("ID_VENTA") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "DETALLE_VENTA_FK2" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES  "PRODUCTO" ("ID_PRODUCTO") ON DELETE CASCADE ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_DETALLE_VENTA" 
  before insert on "DETALLE_VENTA"               
  for each row  
begin   
    select "DETALLE_VENTA_SEQ1".nextval into :NEW.ID_DETALLE_VENTA from dual; 
end; 

/
ALTER TRIGGER  "BI_DETALLE_VENTA" ENABLE
/
CREATE TABLE  "COMPRA" 
   (	"ID_COMPRA" NUMBER, 
	"MONTO_TOTAL" NUMBER, 
	"FECHA" VARCHAR2(20), 
	"HORA" VARCHAR2(20), 
	 CONSTRAINT "COMPRA_PK" PRIMARY KEY ("ID_COMPRA") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_COMPRA" 
  before insert on "COMPRA"               
  for each row  
begin   
    select "COMPRA_SEQ1".nextval into :NEW.ID_COMPRA from dual; 
end; 

/
ALTER TRIGGER  "BI_COMPRA" ENABLE
/
CREATE TABLE  "DETALLE_COMPRA" 
   (	"ID_DETALLE_COMPRA" NUMBER, 
	"ID_COMPRA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" NUMBER, 
	 CONSTRAINT "DETALLE_COMPRA_PK" PRIMARY KEY ("ID_DETALLE_COMPRA") ENABLE, 
	 CONSTRAINT "DETALLE_COMPRA_FK" FOREIGN KEY ("ID_COMPRA")
	  REFERENCES  "COMPRA" ("ID_COMPRA") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "DETALLE_COMPRA_FK2" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES  "PRODUCTO" ("ID_PRODUCTO") ON DELETE CASCADE ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_DETALLE_COMPRA" 
  before insert on "DETALLE_COMPRA"               
  for each row  
begin   
    select "DETALLE_COMPRA_SEQ1".nextval into :NEW.ID_DETALLE_COMPRA from dual; 
end; 

/
ALTER TRIGGER  "BI_DETALLE_COMPRA" ENABLE
/
